spring:
   data:
      mongodb:
         database: expense_db
         host: ds143156.mlab.com
         port: 43156
         username: dbuser
         password: dbuser1
server:
   port: 8083
eureka:
   client:
      serviceUrl:
         defaultZone: http://expense_eureka:8761/eureka