spring:
   jpa:
      hibernate:
         ddl-auto: none
   datasource:
      url: jdbc:mysql://localhost:3306/expense
      username: root
      password: root
server:
   port: 8081
eureka:
   client:
      serviceUrl:
         defaultZone: http://expense_eureka:8761/eureka