spring:
   data:
      mongodb:
         uri: mongodb://dbuser:dbuser1@ds143156.mlab.com:43156/expense_db
server:
   port: 8083
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka