spring:
   datasource:
      url: jdbc:mysql://localhost:3306/expense
      username: root
      password: root
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: none
server:
   port: 9000
logging:
   level:
      org:
         springframework: DEBUG